Fixed CMake build script
TA-Lib/ta-lib pull request #9
Opened 2023-03-07 08:50 UTC by cpp4ever

2023-11-09 03:01 UTC, YmdTb requested changes
This CMake fille works.

2023-12-28 20:31 UTC, bukowa commented
Thank you. Wondering how to build both 32 and 64 for Windows.

2024-02-01 22:04 UTC, geiseri commented
Could this get merged?

2024-03-22 22:11 UTC, merged

2024-03-22 22:13 UTC, mario4tier commented
Thanks all for contributing/verifying.